name: spacerocks
channels:
  - default
  - conda-forge
dependencies:
  - python
  - pytest
  - pylint
  - flake8
  - healpy
  - rebound
  - numpy
  - pandas
  - numba
  - ephem
  - skyfield
  - astropy
  - matplotlib
  - cartopy
