[package]
name = "spacerocks"
version = "3.0.0-alpha.0"
edition = "2021"

[lib]
name = "spacerocks"
crate-type = ["cdylib"]

[dependencies]
spacerocks = { path = "../" }
pyo3 = { version = "*", features = ["extension-module"] }
numpy = "*"
rayon = "*"
nalgebra = "*"