# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
# ['ubuntu-latest', 'macos-latest', 'windows-latest']

name: spacerocks
on: [push]


jobs:

  build:

    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        python-version: [3.8]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: 'latest'
          python-version: ${{ matrix.python-version }}
          environment-file: environment.yml
          activate-environment: spacerocks

      - name: Install Dependencies Absent From Conda
        run: |
          python -m pip install --upgrade pip
          pip install healpy
          pip install .

      - name: Lint with flake8
        shell: pwsh
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --statistics

      - name: Test with pytest
        run: python -m pytest
